name: Gemini ChatBox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.8
  - python-dotenv
  - pip
  - google-generativeai==0.4.0
  - keras==2.12.0
  - numpy==1.23.5
  - pandas==2.2.1
  - pillow==10.2.0
  - scipy==1.12.0
  - streamlit==1.32.0
  - tensorflow-macos==2.12.0
